# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Alias CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          make install-homebrew
          make
          make install-gvm
